using Unity.Cinemachine;
using UnityEngine;

/// <summary>
/// ğŸ‰
/// </summary>
public class GameManager : MonoBehaviour
{
    /// <summary>
    /// è§†è·èŒƒå›´
    /// </summary>
    [SerializeField]
    Vector2 viewRange;

    [SerializeField]
    float scrollSpeed = 1f; // æ»šåŠ¨è°ƒæ•´çš„é€Ÿåº¦

    InputSystem_Actions inputActions;

    /// <summary>
    /// æ™ºèƒ½é•œå¤´æ§åˆ¶å™¨ä¸­æ§åˆ¶é•œå¤´æ—‹è½¬çš„ç»„ä»¶ã€‚
    /// </summary>
    CinemachineInputAxisController cinemaController;
    CinemachineOrbitalFollow orbitalFollow;

    private void Awake()
    {
        inputActions = new();
        cinemaController = FindFirstObjectByType<CinemachineInputAxisController>();
        orbitalFollow = cinemaController.transform.GetComponent<CinemachineOrbitalFollow>();
        cinemaController.enabled = false;
    }

    private void OnEnable()
    {
        // é€šè¿‡ç›‘æ§è§¦ç¢°å¯ç”¨å’Œç¦ç”¨æ¥å®ç°æ˜¯å¦é•œå¤´å¯æ—‹è½¬
        inputActions.Enable();
        inputActions.Player.Attack.started += ctx => cinemaController.enabled = true;
        inputActions.Player.Attack.canceled += ctx => cinemaController.enabled = false;
        // é€šè¿‡æ»šè½®æ¥è°ƒæ•´è§†è·
        inputActions.UI.ScrollWheel.performed += ctx => orbitalFollow.Radius = Mathf.Clamp(orbitalFollow.Radius + ctx.ReadValue<Vector2>().y * scrollSpeed, viewRange.x, viewRange.y);
    }

    private void OnDisable()
    {
        inputActions.Disable();
        inputActions.Player.Attack.started -= ctx => cinemaController.enabled = true;
        inputActions.Player.Attack.canceled -= ctx => cinemaController.enabled = false;
        inputActions.UI.ScrollWheel.performed += ctx => orbitalFollow.Radius = Mathf.Clamp(orbitalFollow.Radius + ctx.ReadValue<Vector2>().y * scrollSpeed, viewRange.x, viewRange.y);
    }


}
